<!DOCTYPE html>
<html lang="ca">
<head>
<title>Cursa</title>
<meta charset="utf-8">
<link rel="stylesheet" href="examen.css">
<script type="text/javascript" src="alerta_plazas.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
</head>
<body>
<header>
<nav class="navbar navbar-inverse">
<div class="container-fluid"></div>
<div class="navbar-header">
<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="modal-dialog" aria-expanded="false">
    <span class="icon-bar"></span>
    <span class="icon bar"></span>
    <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="PAGINA.PHP">Cursa 1 de Març</a>
</div>
<div class="collapse navbar-collapse" id="#">
<ul class="nav navbar-nav" >
    <li class="active"><a href="Fanatics_esports.PHP">Fanatics dels esports<span class="sr-only"></span></a></li>
</ul>
</div>
</nav>
</header>
<div class="container">
<div class="row">
    <div class="col-md-6">
        <h3>¡Corre amb nosaltres!</h3>
        <p>Participa en aquesta impressionant cursa en el passeig maratim acompañat amb grans famosos tant del mon de internet com altres ambits!</p>
    </div>
    <div class="col-md-6">
        <img class="img-responsive" src="nakamura.jpg" alt="Nakamura, jugador profesional de blitz">
    </div>

</div>
</div>
</body>
</html>